#pragma once

/* OLED */
#define OLED_DISPLAY_128X64
#define OLED_IC OLED_IC_SH1106
#define OLED_DC_PIN GP23
#define OLED_CS_PIN GP22
#define OLED_RST_PIN GP24
#define OLED_SPI_DIVISOR 4
#define OLED_COLUMN_OFFSET 2

/* ChibiOS SPI definitions */
#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP26
#define SPI_MOSI_PIN GP27
#define SPI_MISO_PIN GP28

/* RGB MATRIX */
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 180
#define RGB_MATRIX_TIMEOUT 30000
#define RGB_MATRIX_SLEEP

/* MAGIC BOOT */
#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 11

/* CIRQUE TRACKPAD*/
#define CIRQUE_PINNACLE_SPI_CS_PIN 25
#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_ROTATION_270
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
